-- MySQL Script generated by MySQL Workbench
-- Thu Dec 26 02:39:25 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema parking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema parking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parking` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `parking` ;

-- -----------------------------------------------------
-- Table `parking`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking`.`driver` (
  `driver_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `license_plate` VARCHAR(20) NOT NULL,
  `payment_method` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`driver_id`),
  UNIQUE INDEX `license_plate` (`license_plate` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `parking`.`parking_lots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking`.`parking_lots` (
  `lot_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `location` POINT NOT NULL,
  `capacity` INT NULL DEFAULT '0',
  PRIMARY KEY (`lot_id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `parking`.`lot_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking`.`lot_admin` (
  `lot_admin_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `lot_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`lot_admin_id`),
  INDEX `lot_id` (`lot_id` ASC) VISIBLE,
  CONSTRAINT `lot_admin_ibfk_1`
    FOREIGN KEY (`lot_id`)
    REFERENCES `parking`.`parking_lots` (`lot_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `parking`.`parking_spots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking`.`parking_spots` (
  `spot_id` INT NOT NULL AUTO_INCREMENT,
  `lot_id` INT NOT NULL,
  `status` ENUM('available', 'occupied', 'reserved') NULL DEFAULT 'available',
  `type` ENUM('regular', 'disabled', 'ev_charging') NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`spot_id`),
  INDEX `lot_id` (`lot_id` ASC) VISIBLE,
  CONSTRAINT `parking_spots_ibfk_1`
    FOREIGN KEY (`lot_id`)
    REFERENCES `parking`.`parking_lots` (`lot_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `parking`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking`.`reservations` (
  `resv_id` INT NOT NULL AUTO_INCREMENT,
  `driver_id` INT NOT NULL,
  `spot_id` INT NOT NULL,
  `start_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `end_time` TIMESTAMP NULL DEFAULT NULL,
  `status` ENUM('active', 'confirmed', 'expired', 'canceled') NULL DEFAULT 'active',
  `penalty` DECIMAL(10,2) NULL DEFAULT '0.00',
  PRIMARY KEY (`resv_id`),
  INDEX `driver_id` (`driver_id` ASC) VISIBLE,
  INDEX `spot_id` (`spot_id` ASC) VISIBLE,
  CONSTRAINT `reservations_ibfk_1`
    FOREIGN KEY (`driver_id`)
    REFERENCES `parking`.`driver` (`driver_id`),
  CONSTRAINT `reservations_ibfk_2`
    FOREIGN KEY (`spot_id`)
    REFERENCES `parking`.`parking_spots` (`spot_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `parking`.`sys_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking`.`sys_admin` (
  `sys_admin_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`sys_admin_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `parking`.`top_lots`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking`.`top_lots` (
  `lot_id` INT NOT NULL,
  `revenue` DECIMAL(10,2) NULL DEFAULT '0.00',
  `is_top` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`lot_id`),
  CONSTRAINT `top_lots_ibfk_1`
    FOREIGN KEY (`lot_id`)
    REFERENCES `parking`.`parking_lots` (`lot_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `parking`.`top_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking`.`top_users` (
  `driver_id` INT NOT NULL,
  `number_of_resvs` INT NULL DEFAULT '1',
  `is_top` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`driver_id`),
  CONSTRAINT `top_users_ibfk_1`
    FOREIGN KEY (`driver_id`)
    REFERENCES `parking`.`driver` (`driver_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `parking`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parking`.`transactions` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `driver_id` INT NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `payment_status` ENUM('pending', 'completed') NULL DEFAULT 'pending',
  PRIMARY KEY (`transaction_id`),
  INDEX `driver_id` (`driver_id` ASC) VISIBLE,
  CONSTRAINT `transactions_ibfk_1`
    FOREIGN KEY (`driver_id`)
    REFERENCES `parking`.`driver` (`driver_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
